/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cilix.Vista;

import Controlador.*;
import Modelo.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emanuel
 */
public class FrmNewTransaccion extends javax.swing.JDialog {
    ProductoBL logNegProd = new ProductoBL();
    ClienteNaturalBL logNegCliNat = new ClienteNaturalBL();
    EmpresaBL logNegEmpresa = new EmpresaBL();
    TransaccionTipoBL logNegTipo = new TransaccionTipoBL();
    
    ArrayList<Producto> productos = new ArrayList<Producto>();
    ArrayList<ClienteNatural> clientesNat = new ArrayList<ClienteNatural>();
    ArrayList<Empresa> empresas = new ArrayList<Empresa>();
    ArrayList<TransaccionTipo> tipos = new ArrayList<TransaccionTipo>();
    
    Usuario user;
    int idProducto = -1;
    int cantidadActual = -1;
    double precio = -1;
    int cantidadComprar = 0;
    int idCliente = -1;
    String descripcion = "";
    int tipoCliente;
    
    public FrmNewTransaccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
    }
    
    /*ESTE CONSTRUCTOR ES EL QUE SE INVOCA*/
    public FrmNewTransaccion(java.awt.Frame parent, boolean modal, Usuario user) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
        this.user = user;
        
        productos = logNegProd.devolverProductos();
        for(int i=0; i<productos.size();i++){
            jCboProd.addItem(productos.get(i).getNombre());

        }
        AutoCompletion.enable(jCboProd);
        tipos = logNegTipo.devolverTipos();
        for (int i=0;i<tipos.size();i++){
            jCboTipo.addItem(tipos.get(i).getDescriptor());
        }
        AutoCompletion.enable(jCboTipo);
        clientesNat = logNegCliNat.devolverClientesNaturales(-1, "","","","","");
        for (int i=0;i<clientesNat.size();i++){
            jCboCliPro.addItem(clientesNat.get(i).getNombre()+" "+clientesNat.get(i).getApellido());
        }
        empresas = logNegEmpresa.devolverEmpresas("","","");
        for (int i=0;i<empresas.size();i++){
            jCboCliPro.addItem(empresas.get(i).getRazonSocial());
        }
        AutoCompletion.enable(jCboCliPro);
    }

    
    public Usuario getUser() {
        return user;
    }

    public void setUser(Usuario user) {
        this.user = user;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidadActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jCboProd = new javax.swing.JComboBox<>();
        jCboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCboCliPro = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtCantidadActual.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Producto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad actual");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cantidad");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cliente/Proveedor");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Descripcion");

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jCboProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCboProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProdActionPerformed(evt);
            }
        });

        jCboTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboTipoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de transacción");

        jCboCliPro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(52, 52, 52)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCboCliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnAceptar)
                        .addGap(48, 48, 48)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCboTipo, 0, 280, Short.MAX_VALUE)
                                .addComponent(jCboProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidadActual)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCboCliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean isEmpty(javax.swing.JTextField x){
        return x.getText().equals("");
    }
    
    private boolean isEmpty(javax.swing.JTextArea x){
        return x.getText().equals("");
    }
    
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        TransaccionBL logNegTrans= new TransaccionBL();
        String prod =jCboProd.getSelectedItem().toString();
        String tipo =jCboTipo.getSelectedItem().toString();
        String contacto =jCboCliPro.getSelectedItem().toString();
        
        /*Te deje el ejemplo :D*/
        Producto prodObj = new Producto();
        for(int i = 0; i < productos.size(); ++i){
            if(productos.get(i).getNombre().equals(prod)){
                prodObj = productos.get(i);
                break;
            }
        }
        
        TransaccionTipo tipoObj = new TransaccionTipo();
        for(int i = 0; i < tipos.size(); ++i){
            if(tipos.get(i).getDescriptor().equals(tipo)){
                tipoObj = tipos.get(i);
                break;
            }
        }
        
        ClienteNatural cli = null;
        for(int i = 0; i < clientesNat.size(); ++i){
            if((tipoObj.getDescriptor().equals("Venta")) && ((clientesNat.get(i).getNombre()+" "+clientesNat.get(i).getApellido()).equals(contacto))){
                cli = clientesNat.get(i);
                break;
            }
        }
        Empresa emp = null;
        if(cli==null){            
            for(int i = 0; i < empresas.size(); ++i){
                if((empresas.get(i).getRazonSocial()).equals(contacto)){
                    String tipoEj=empresas.get(i).getTipo();
                    if(tipoEj.equals("Cliente") && tipoObj.getDescriptor().equals("Venta")) {
                        emp = empresas.get(i);
                        break;
                    }
                    else if(tipoEj.equals("Proveedor") && tipoObj.getDescriptor().equals("Compra")){
                        emp = empresas.get(i);
                        break;
                    }                     
                }
            }            
        }
        
        String desc = txtDescripcion.getText();
        
        Transaccion t= new Transaccion();
        t.setProducto(prodObj);
        int cantActual = Integer.parseInt(txtCantidadActual.getText());
        int cant = Integer.parseInt(txtCantidad.getText());
        t.setCantidad(cant);
        t.setDescripcion(desc);
        if(cli!=null) t.setClienteNatural(cli);
        if(emp!=null) t.setEmpresa(emp);
        t.setTipoTransaccion(tipoObj);
        t.setUsuario(user);
        
        if(tipoObj.getDescriptor().equals("Venta")){
            if(cant>cantActual){
                JOptionPane.showMessageDialog(null,"No existen suficientes items de ese producto");
                return;
            }
            else{
                if(logNegTrans.registrarTransaccion(t)){
                    JOptionPane.showMessageDialog(null,"Registro Exitoso!");
                    dispose();

                    return;
                };                
            }
            
        }
        else{
                if(logNegTrans.registrarTransaccion(t)){
                    JOptionPane.showMessageDialog(null,"Registro Exitoso!");
                                        dispose();

                    return;
                };                
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboTipoActionPerformed
        if((jCboTipo.getSelectedItem().toString()).equals("Compra")){
            jCboCliPro.removeAllItems();
            for (int i=0;i<empresas.size();i++){
                jCboCliPro.addItem(empresas.get(i).getRazonSocial());
            }
        }
        if((jCboTipo.getSelectedItem().toString()).equals("Venta")){
            jCboCliPro.removeAllItems();
            
            for (int i=0;i<clientesNat.size();i++){
                jCboCliPro.addItem(clientesNat.get(i).getNombre()+" "+clientesNat.get(i).getApellido());
            }
            for (int i=0;i<empresas.size();i++){
                jCboCliPro.addItem(empresas.get(i).getRazonSocial());
            }
        }
    }//GEN-LAST:event_jCboTipoActionPerformed

    private void jCboProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProdActionPerformed
        String producto = jCboProd.getSelectedItem().toString();
        Producto prodObj = new Producto();
        for(int i=0;i<productos.size();++i){
            if(productos.get(i).getNombre().equals(producto)){
                prodObj = productos.get(i);
                break;
            }
        }
        int cant= prodObj.getCantidad();
        
        txtCantidadActual.setText(Integer.toString(cant));
    }//GEN-LAST:event_jCboProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNewTransaccion dialog = new FrmNewTransaccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jCboCliPro;
    private javax.swing.JComboBox<String> jCboProd;
    private javax.swing.JComboBox<String> jCboTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
